/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Does not check downstream dependencies.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Info */
        get: operations["app_info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap Config
         * @description Self-describing config payload. Unauthenticated. No secrets.
         */
        get: operations["bootstrap_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Labels Lookup */
        get: operations["labels_lookup_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Dashboard */
        get: operations["user_dashboard_me_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings Read All */
        get: operations["settings_read_all_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings Read One */
        get: operations["settings_read_one_settings__key__get"];
        /** Settings Write One */
        put: operations["settings_write_one_settings__key__put"];
        post?: never;
        /** Settings Delete One */
        delete: operations["settings_delete_one_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forms Autocomplete */
        get: operations["forms_autocomplete_forms_autocomplete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Summary
         * @description Period totals: request count, unique visitors, status mix, mean latency.
         */
        get: operations["metrics_summary_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/timeseries/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Daily Series
         * @description One ``(bucket, request_count, unique_visitors)`` point per day.
         */
        get: operations["metrics_daily_series_metrics_timeseries_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/top-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Top Resources
         * @description The ``limit`` most-requested resources, ordered by request count.
         */
        get: operations["metrics_top_resources_metrics_top_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/geography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Geography
         * @description Per-country counts, descending by request count.
         */
        get: operations["metrics_geography_metrics_geography_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{distribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Download */
        get: operations["data_download_data__distribution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{distribution_id}/sparql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Sparql Get */
        get: operations["data_sparql_get_data__distribution_id__sparql_get"];
        put?: never;
        /** Data Sparql Post */
        post: operations["data_sparql_post_data__distribution_id__sparql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sparql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sparql Get */
        get: operations["sparql_get_sparql_get"];
        put?: never;
        /** Sparql Post */
        post: operations["sparql_post_sparql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Root Spec */
        get: operations["ext_root_spec_spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{url_prefix}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Type Spec */
        get: operations["ext_type_spec__url_prefix__spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{url_prefix}/{record_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Instance Spec */
        get: operations["ext_instance_spec__url_prefix___record_id__spec_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Root Expanded */
        get: operations["ext_root_expanded_expanded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{url_prefix}/{record_id}/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Instance Expanded */
        get: operations["ext_instance_expanded__url_prefix___record_id__expanded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/{child_prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Root Page */
        get: operations["ext_root_page_page__child_prefix__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{url_prefix}/{record_id}/page/{child_prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ext Instance Page */
        get: operations["ext_instance_page__url_prefix___record_id__page__child_prefix__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rd List */
        get: operations["rd_list_resource_definitions_get"];
        put?: never;
        /**
         * Rd Create
         * @description Register a new metadata type (admin only).
         *
         *     Exposing a type is a two-step act (ADR-0009): **first** publish the
         *     type's SHACL shape as a record (e.g. ``PUT`` the shape graph to a
         *     base-relative IRI such as ``{base}/shapes/Ontology`` through the LDP
         *     API), **then** register a resource definition here whose ``schema``
         *     points at that shape IRI. This call rejects a ``schema`` that does not
         *     resolve to a published SHACL shape, so the order matters. On success
         *     the type's LDP endpoints (``/{urlPrefix}`` …) and OpenAPI paths appear
         *     immediately — no restart.
         */
        post: operations["rd_create_resource_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-definitions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rd Get */
        get: operations["rd_get_resource_definitions__slug__get"];
        /**
         * Rd Replace
         * @description Replace an existing definition (admin only).
         *
         *     The whole definition is replaced, including its ``children`` — this is
         *     how a child link is added to an existing type (e.g. give Catalog a
         *     ``children`` entry targeting a new Ontology type so catalogs can hold
         *     ontology records). The body's ``urlPrefix``/``name`` must keep the same
         *     slug; renaming is a create, not a replace. As with create, ``schema``
         *     must resolve to a published SHACL shape.
         */
        put: operations["rd_replace_resource_definitions__slug__put"];
        post?: never;
        /** Rd Delete */
        delete: operations["rd_delete_resource_definitions__slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ldp Get */
        get: operations["ldp_get__path__get"];
        /** Ldp Put */
        put: operations["ldp_put__path__put"];
        /** Ldp Post */
        post: operations["ldp_post__path__post"];
        /** Ldp Delete */
        delete: operations["ldp_delete__path__delete"];
        /** Ldp Options */
        options: operations["ldp_options__path__options"];
        /** Ldp Head */
        head: operations["ldp_head__path__head"];
        /** Ldp Patch */
        patch: operations["ldp_patch__path__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppInfo
         * @description Response shape for ``GET /info``.
         */
        AppInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            build: components["schemas"]["BuildInfo"];
            runtime: components["schemas"]["RuntimeInfo"];
        };
        /**
         * AutocompleteResponse
         * @description Response shape for ``GET /forms/autocomplete``.
         */
        AutocompleteResponse: {
            /** Items */
            items: components["schemas"]["AutocompleteResultItem"][];
        };
        /**
         * AutocompleteResultItem
         * @description One item in the autocomplete response.
         */
        AutocompleteResultItem: {
            /** Iri */
            iri: string;
            /** Label */
            label: string;
            /** Source */
            source: string;
        };
        /**
         * BootstrapConfig
         * @description Self-description payload returned from ``GET /config``.
         */
        BootstrapConfig: {
            /** Fdp Url */
            fdp_url: string;
            /** Fdp Namespace */
            fdp_namespace: string;
            /** Fdp Version */
            fdp_version: string;
            oidc: components["schemas"]["OIDCBootstrap"];
            profile: components["schemas"]["ProfileBootstrap"] | null;
            features: components["schemas"]["FeatureFlags"];
        };
        /**
         * BuildInfo
         * @description Build-time metadata.
         *
         *     All fields are optional because they are populated from environment
         *     variables the build pipeline sets (``FDP_BUILD_COMMIT``,
         *     ``FDP_BUILD_BUILT_AT``). A locally-developed checkout has no values
         *     and the client renders "(unknown build)".
         */
        BuildInfo: {
            /** Commit */
            commit?: string | null;
            /** Built At */
            built_at?: string | null;
        };
        /**
         * CheckOutcome
         * @description One dependency's probe result.
         */
        CheckOutcome: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "fail";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * ChildLinkInput
         * @description A child link in a create/replace request (unresolved form).
         */
        ChildLinkInput: {
            /** Relationuri */
            relationUri: string;
            /** Target */
            target: string;
            /**
             * Title
             * @default
             */
            title: string;
            /** Tagsuri */
            tagsUri?: string | null;
        };
        /**
         * ChildLinkView
         * @description A resolved child link in a read response.
         */
        ChildLinkView: {
            /** Relationuri */
            relationUri: string;
            /** Target */
            target: string;
            /** Targetname */
            targetName: string;
            /** Targetschema */
            targetSchema: string;
            /** Title */
            title: string;
            /** Tagsuri */
            tagsUri?: string | null;
        };
        /** CountryModel */
        CountryModel: {
            /**
             * Country Code
             * @description ISO 3166-1 alpha-2. NULL when GeoLite2 produced no answer.
             */
            country_code?: string | null;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** DailyPointModel */
        DailyPointModel: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** DailySeriesResponse */
        DailySeriesResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Points */
            points: components["schemas"]["DailyPointModel"][];
        };
        /**
         * DashboardItem
         * @description One record summary surfaced on the dashboard.
         */
        DashboardItem: {
            /** Record Iri */
            record_iri: string;
            /** Type Iri */
            type_iri?: string | null;
            /** Title */
            title?: string | null;
            /** Last Modified */
            last_modified?: string | null;
        };
        /**
         * DashboardResponse
         * @description Response shape for ``GET /me/dashboard``.
         */
        DashboardResponse: {
            /** Owned */
            owned: components["schemas"]["DashboardItem"][];
            /** Editable */
            editable: components["schemas"]["DashboardItem"][];
            /** Recent */
            recent: components["schemas"]["DashboardItem"][];
        };
        /**
         * FeatureFlags
         * @description Coarse feature flags surfaced to the client.
         *
         *     The client hides any UI that depends on a feature whose flag is
         *     ``False``. Flags reflect what the server actually exposes — not what
         *     the deployment *could* be configured to enable.
         */
        FeatureFlags: {
            /** Metrics */
            metrics: boolean;
            /** Sparql */
            sparql: boolean;
            /** Data Provider */
            data_provider: boolean;
            /**
             * Search
             * @default false
             */
            search: boolean;
            /**
             * Index
             * @default false
             */
            index: boolean;
        };
        /** GeographyResponse */
        GeographyResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Countries */
            countries: components["schemas"]["CountryModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LabelsResponse
         * @description Response shape for ``GET /labels``.
         */
        LabelsResponse: {
            /** Labels */
            labels: {
                [key: string]: string;
            };
        };
        /**
         * OIDCBootstrap
         * @description OIDC endpoint hints for the client.
         *
         *     The issuer's ``.well-known/openid-configuration`` is the authoritative
         *     source for endpoint URLs; the client uses it to discover the
         *     authorization, token, and JWKS endpoints. We expose only the issuer
         *     and audience here, plus a non-binding ``client_id_hint`` so a stock
         *     client can pre-fill its OIDC registration if the operator hasn't
         *     customised it.
         */
        OIDCBootstrap: {
            /** Issuer */
            issuer: string;
            /** Audience */
            audience: string;
            /** Client Id Hint */
            client_id_hint?: string | null;
        };
        /**
         * PeriodInfo
         * @description Resolved period bounds echoed on every response.
         */
        PeriodInfo: {
            /**
             * Since
             * Format: date
             */
            since: string;
            /**
             * Until
             * Format: date
             */
            until: string;
        };
        /**
         * ProfileBootstrap
         * @description Currently-applied deployment profile.
         */
        ProfileBootstrap: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * ReadinessReport
         * @description Response shape for ``GET /readyz``.
         */
        ReadinessReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["CheckOutcome"];
            };
        };
        /**
         * ResourceDefinitionInput
         * @description Create/replace request body for a resource definition.
         */
        ResourceDefinitionInput: {
            /** Urlprefix */
            urlPrefix: string;
            /** Name */
            name: string;
            /** Schema */
            schema: string;
            /** Children */
            children?: components["schemas"]["ChildLinkInput"][];
        };
        /**
         * ResourceDefinitionListView
         * @description Response for ``GET /resource-definitions`` — the full type catalog.
         */
        ResourceDefinitionListView: {
            /** Definitions */
            definitions: components["schemas"]["ResourceDefinitionView"][];
        };
        /**
         * ResourceDefinitionView
         * @description A resolved resource definition in a read response.
         */
        ResourceDefinitionView: {
            /** Slug */
            slug: string;
            /** Urlprefix */
            urlPrefix: string;
            /** Name */
            name: string;
            /** Schema */
            schema: string;
            /** Isroot */
            isRoot: boolean;
            /** Children */
            children: components["schemas"]["ChildLinkView"][];
        };
        /**
         * RuntimeInfo
         * @description Runtime metadata: which Python is the server actually running on.
         */
        RuntimeInfo: {
            /** Python Version */
            python_version: string;
        };
        /**
         * SettingsResponse
         * @description Shape returned by ``GET /settings``.
         *
         *     The settings are wrapped in a top-level ``values`` dict keyed by
         *     registered key so adding a new key doesn't break clients that
         *     iterate.
         */
        SettingsResponse: {
            /** Values */
            values: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /**
         * SettingsValueResponse
         * @description Shape returned by ``GET /settings/{key}``.
         */
        SettingsValueResponse: {
            /** Key */
            key: string;
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /** SummaryResponse */
        SummaryResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
            /** Latency Ms Avg */
            latency_ms_avg: number | null;
            /** Status 2Xx Count */
            status_2xx_count: number;
            /** Status 3Xx Count */
            status_3xx_count: number;
            /** Status 4Xx Count */
            status_4xx_count: number;
            /** Status 5Xx Count */
            status_5xx_count: number;
        };
        /** TopResourceModel */
        TopResourceModel: {
            /** Resource Iri */
            resource_iri: string;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** TopResourcesResponse */
        TopResourcesResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Event Type */
            event_type?: string | null;
            /** Items */
            items: components["schemas"]["TopResourceModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    app_info_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfo"];
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReport"];
                };
            };
        };
    };
    bootstrap_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapConfig"];
                };
            };
        };
    };
    labels_lookup_labels_get: {
        parameters: {
            query: {
                /** @description One or more IRIs to resolve. Repeat the parameter. */
                iri: string[];
                /** @description Preferred BCP-47 language tag. Untagged literals are the fallback. */
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_dashboard_me_dashboard_get: {
        parameters: {
            query?: {
                /** @description Maximum records in 'owned'. */
                owned_limit?: number;
                /** @description Maximum records in 'recent'. */
                recent_limit?: number;
                /** @description Maximum records in 'editable'. */
                editable_limit?: number;
                /** @description Drop the subject filter and return system-wide results. Requires the admin role. */
                as_admin?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_read_all_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    settings_read_one_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsValueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_write_one_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsValueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_delete_one_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forms_autocomplete_forms_autocomplete_get: {
        parameters: {
            query: {
                /** @description Name of the configured autocomplete source. */
                source: string;
                /** @description Case-insensitive prefix to match. */
                prefix?: string;
                /** @description Maximum items returned. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutocompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_summary_metrics_summary_get: {
        parameters: {
            query?: {
                /** @description Inclusive start date. */
                since?: string | null;
                /** @description Inclusive end date. */
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_daily_series_metrics_timeseries_daily_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_top_resources_metrics_top_resources_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                event_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopResourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_geography_metrics_geography_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_download_data__distribution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_sparql_get_data__distribution_id__sparql_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_sparql_post_data__distribution_id__sparql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sparql_get_sparql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sparql_post_sparql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ext_root_spec_spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ext_type_spec__url_prefix__spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                url_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ext_instance_spec__url_prefix___record_id__spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                url_prefix: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ext_root_expanded_expanded_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ext_instance_expanded__url_prefix___record_id__expanded_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                url_prefix: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ext_root_page_page__child_prefix__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                child_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ext_instance_page__url_prefix___record_id__page__child_prefix__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                url_prefix: string;
                record_id: string;
                child_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rd_list_resource_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDefinitionListView"];
                };
            };
        };
    };
    rd_create_resource_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceDefinitionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDefinitionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rd_get_resource_definitions__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDefinitionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rd_replace_resource_definitions__slug__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceDefinitionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceDefinitionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rd_delete_resource_definitions__slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_get__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_put__path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_post__path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_delete__path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_options__path__options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_head__path__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_patch__path__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
