/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. Does not check downstream dependencies.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Summary
         * @description Period totals: request count, unique visitors, status mix, mean latency.
         */
        get: operations["metrics_summary_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/timeseries/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Daily Series
         * @description One ``(bucket, request_count, unique_visitors)`` point per day.
         */
        get: operations["metrics_daily_series_metrics_timeseries_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/top-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Top Resources
         * @description The ``limit`` most-requested resources, ordered by request count.
         */
        get: operations["metrics_top_resources_metrics_top_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/geography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Geography
         * @description Per-country counts, descending by request count.
         */
        get: operations["metrics_geography_metrics_geography_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{distribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Download */
        get: operations["data_download_data__distribution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/{distribution_id}/sparql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Sparql Get */
        get: operations["data_sparql_get_data__distribution_id__sparql_get"];
        put?: never;
        /** Data Sparql Post */
        post: operations["data_sparql_post_data__distribution_id__sparql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sparql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sparql Get */
        get: operations["sparql_get_sparql_get"];
        put?: never;
        /** Sparql Post */
        post: operations["sparql_post_sparql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ldp Get */
        get: operations["ldp_get__path__get"];
        /** Ldp Put */
        put: operations["ldp_put__path__put"];
        /** Ldp Post */
        post: operations["ldp_post__path__post"];
        /** Ldp Delete */
        delete: operations["ldp_delete__path__delete"];
        /** Ldp Options */
        options: operations["ldp_options__path__options"];
        /** Ldp Head */
        head: operations["ldp_head__path__head"];
        /** Ldp Patch */
        patch: operations["ldp_patch__path__patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a Repository
         * @description Fetch the RDF graph for one Repository record.
         */
        get: operations["getRepository"];
        /**
         * Replace a Repository
         * @description Replace the RDF graph for one Repository record.
         */
        put: operations["replaceRepository"];
        post?: never;
        /**
         * Delete a Repository
         * @description Remove a Repository and its sibling /meta and /audit graphs.
         */
        delete: operations["deleteRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SHACL shape for Repository
         * @description Return the SHACL shape graph that validates Repository instances (https://w3id.org/fdp/o#Repository).
         */
        get: operations["getRepositorySpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repository with parents
         * @description Return the Repository record together with every ancestor reachable via dct:isPartOf.
         */
        get: operations["getRepositoryExpanded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/page/{childPrefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a page of Repository children
         * @description Paginated listing of Repository members of a given child type. ``childPrefix`` is the URL prefix of the target type.
         */
        get: operations["getRepositoryChildPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Catalog
         * @description Create a new Catalog member. The server mints the resource IRI; pass the ``Slug`` header to suggest a suffix.
         */
        post: operations["createCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a Catalog
         * @description Fetch the RDF graph for one Catalog record.
         */
        get: operations["getCatalog"];
        /**
         * Replace a Catalog
         * @description Replace the RDF graph for one Catalog record.
         */
        put: operations["replaceCatalog"];
        post?: never;
        /**
         * Delete a Catalog
         * @description Remove a Catalog and its sibling /meta and /audit graphs.
         */
        delete: operations["deleteCatalog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SHACL shape for Catalog
         * @description Return the SHACL shape graph that validates Catalog instances (http://www.w3.org/ns/dcat#Catalog).
         */
        get: operations["getCatalogSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{id}/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog with parents
         * @description Return the Catalog record together with every ancestor reachable via dct:isPartOf.
         */
        get: operations["getCatalogExpanded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{id}/page/{childPrefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a page of Catalog children
         * @description Paginated listing of Catalog members of a given child type. ``childPrefix`` is the URL prefix of the target type.
         */
        get: operations["getCatalogChildPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Dataset
         * @description Create a new Dataset member. The server mints the resource IRI; pass the ``Slug`` header to suggest a suffix.
         */
        post: operations["createDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a Dataset
         * @description Fetch the RDF graph for one Dataset record.
         */
        get: operations["getDataset"];
        /**
         * Replace a Dataset
         * @description Replace the RDF graph for one Dataset record.
         */
        put: operations["replaceDataset"];
        post?: never;
        /**
         * Delete a Dataset
         * @description Remove a Dataset and its sibling /meta and /audit graphs.
         */
        delete: operations["deleteDataset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SHACL shape for Dataset
         * @description Return the SHACL shape graph that validates Dataset instances (http://www.w3.org/ns/dcat#Dataset).
         */
        get: operations["getDatasetSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{id}/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset with parents
         * @description Return the Dataset record together with every ancestor reachable via dct:isPartOf.
         */
        get: operations["getDatasetExpanded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{id}/page/{childPrefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a page of Dataset children
         * @description Paginated listing of Dataset members of a given child type. ``childPrefix`` is the URL prefix of the target type.
         */
        get: operations["getDatasetChildPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a DataService
         * @description Create a new DataService member. The server mints the resource IRI; pass the ``Slug`` header to suggest a suffix.
         */
        post: operations["createDataService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-service/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a DataService
         * @description Fetch the RDF graph for one DataService record.
         */
        get: operations["getDataService"];
        /**
         * Replace a DataService
         * @description Replace the RDF graph for one DataService record.
         */
        put: operations["replaceDataService"];
        post?: never;
        /**
         * Delete a DataService
         * @description Remove a DataService and its sibling /meta and /audit graphs.
         */
        delete: operations["deleteDataService"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-service/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SHACL shape for DataService
         * @description Return the SHACL shape graph that validates DataService instances (http://www.w3.org/ns/dcat#DataService).
         */
        get: operations["getDataServiceSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-service/{id}/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get DataService with parents
         * @description Return the DataService record together with every ancestor reachable via dct:isPartOf.
         */
        get: operations["getDataServiceExpanded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Distribution
         * @description Create a new Distribution member. The server mints the resource IRI; pass the ``Slug`` header to suggest a suffix.
         */
        post: operations["createDistribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a Distribution
         * @description Fetch the RDF graph for one Distribution record.
         */
        get: operations["getDistribution"];
        /**
         * Replace a Distribution
         * @description Replace the RDF graph for one Distribution record.
         */
        put: operations["replaceDistribution"];
        post?: never;
        /**
         * Delete a Distribution
         * @description Remove a Distribution and its sibling /meta and /audit graphs.
         */
        delete: operations["deleteDistribution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get SHACL shape for Distribution
         * @description Return the SHACL shape graph that validates Distribution instances (http://www.w3.org/ns/dcat#Distribution).
         */
        get: operations["getDistributionSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distribution/{id}/expanded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Distribution with parents
         * @description Return the Distribution record together with every ancestor reachable via dct:isPartOf.
         */
        get: operations["getDistributionExpanded"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CountryModel */
        CountryModel: {
            /**
             * Country Code
             * @description ISO 3166-1 alpha-2. NULL when GeoLite2 produced no answer.
             */
            country_code?: string | null;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** DailyPointModel */
        DailyPointModel: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** DailySeriesResponse */
        DailySeriesResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Points */
            points: components["schemas"]["DailyPointModel"][];
        };
        /** GeographyResponse */
        GeographyResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Countries */
            countries: components["schemas"]["CountryModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PeriodInfo
         * @description Resolved period bounds echoed on every response.
         */
        PeriodInfo: {
            /**
             * Since
             * Format: date
             */
            since: string;
            /**
             * Until
             * Format: date
             */
            until: string;
        };
        /** SummaryResponse */
        SummaryResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
            /** Latency Ms Avg */
            latency_ms_avg: number | null;
            /** Status 2Xx Count */
            status_2xx_count: number;
            /** Status 3Xx Count */
            status_3xx_count: number;
            /** Status 4Xx Count */
            status_4xx_count: number;
            /** Status 5Xx Count */
            status_5xx_count: number;
        };
        /** TopResourceModel */
        TopResourceModel: {
            /** Resource Iri */
            resource_iri: string;
            /** Request Count */
            request_count: number;
            /** Unique Visitors */
            unique_visitors: number;
        };
        /** TopResourcesResponse */
        TopResourcesResponse: {
            period: components["schemas"]["PeriodInfo"];
            /** Event Type */
            event_type?: string | null;
            /** Items */
            items: components["schemas"]["TopResourceModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_summary_metrics_summary_get: {
        parameters: {
            query?: {
                /** @description Inclusive start date. */
                since?: string | null;
                /** @description Inclusive end date. */
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_daily_series_metrics_timeseries_daily_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_top_resources_metrics_top_resources_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                event_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopResourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_geography_metrics_geography_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                resource_iri?: string | null;
                event_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeographyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_download_data__distribution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_sparql_get_data__distribution_id__sparql_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_sparql_post_data__distribution_id__sparql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sparql_get_sparql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sparql_post_sparql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ldp_get__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_put__path__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_post__path__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_delete__path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_options__path__options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_head__path__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ldp_patch__path__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Replacement Repository graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRepositorySpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRepositoryExpanded: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRepositoryChildPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL prefix of the child resource type to list. */
                childPrefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description New Catalog graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Replacement Catalog graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCatalogSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCatalogExpanded: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCatalogChildPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
                /** @description URL prefix of the child resource type to list. */
                childPrefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description New Dataset graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Replacement Dataset graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDatasetSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDatasetExpanded: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDatasetChildPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
                /** @description URL prefix of the child resource type to list. */
                childPrefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDataService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description New DataService graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDataService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceDataService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Replacement DataService graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDataService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDataServiceSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDataServiceExpanded: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description New Distribution graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Replacement Distribution graph */
        requestBody: {
            content: {
                "text/turtle": string;
                "application/ld+json": string;
                "application/rdf+xml": string;
                "application/n-triples": string;
            };
        };
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDistributionSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDistributionExpanded: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (path segment). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RDF graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/turtle": string;
                    "application/ld+json": string;
                    "application/rdf+xml": string;
                    "application/n-triples": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
